### ISSUE TITLE
Issues with Atlas (doesnt work)

### ISSUE THREAD

**Issue by haodakei** [laytya/Atlas#12]
Hello, thanks you for your work it's amazing ! I would love to use your version of AtlasLoot because of the enhanced options and databases but when I use both of Atlas & Atlas Loot it doesnt work : 
http://puu.sh/DDyqu/8ad0b6a041.jpg

I also tried to only use your AtlasLoot version on my Atlas 1.8.5a PRE TBC but when I open my Atlas I have one error : 
Number : 9
Error : Interface\AddOns\AtlasLoot\Core\AtlasLoot.lua:658: attempt to index global `ATLAS_DROPDOWNS' (a nil value)

And if I try to select one map/category (like I select Molten Core instance) I dont see it in Atlas.

Is there a way to fix it ? It would be very appreciate !

Regards

**Comment by laytya** [comment]
its working both. 
in your case  - i think you mixed some not compatible versions.

**Comment by Cocio21** [comment]
Not working on Endless (Sunstrider) server.

Client reports it incompatible, server version is 2.4.3

**Comment by laytya** [comment]
this version for 1.12
