### ISSUE TITLE
Карты из каты+

### ISSUE THREAD

**Issue by gamer4eg** [laytya/Atlas#2]
Так как близы удосужились нарисовать простые и главное ПОНЯТНЫЕ с первого взгляда нубу карты, предлагаю перенести их в атлас. Единственное что меня остановило, мне не хватает рук добавить в правом верхнем углу карты атласа переключатель этажа карты.
Так же и с картографером можно.

**Comment by laytya** [comment]
это где? линк?

**Comment by gamer4eg** [comment]
Лови.Там же все остальные карты.
Заменить да маркеры подвинуть.(Если нужно)
Да меню выбора этажа добавить.
http://ru.wowhead.com/maps?data=1584

**Comment by gamer4eg** [comment]
Или тебе распотрошить клиент ретейла и сбросить все карты архивом?Могу.

**Comment by laytya** [comment]
да лучше второе

**Comment by gamer4eg** [comment]
Ок. Займусь завтра.

**Comment by gamer4eg** [comment]
Блин, в клиенте они лежат кусками, сможешь собрать? Так же прикладываю пару сайтов с картами
Вот тут все http://all-infowow.ru/news/2010-08-16-1091


Кстати, а получение координат в инстах никак не реализумемо в ваниле?
Просто если можно получить хотя-бы кокие корды то...
А то я для 335 такое(но там уже в рейдах карты были, мб возможно стало...)

**Comment by Artur91425** [comment]
вы понимаете, что вес аддона будет расти как на дрожжах?) Эти карты с каты, да еще и с этажами раза в 2 будут больше весить... И как ни крути придется ставить метки на эти карты для нормального ориентира по атласу и картам.

**Comment by Artur91425** [comment]
да и на этих картах содержатся названия инстов... Получается для каждой локали аддона нужно будет набор карт иметь)

**Comment by laytya** [comment]
да не, их все нада редактировать, 
я думаю нада их чистить и обрезать, а то поля огроменные
короче как будет время займусь

**Comment by gamer4eg** [comment]
Про вес-берем значится шакалов, и сжимаем, хех)
Про поля и прочее выше уже сказано.
Про метки-нужны только стыки этажей, да черепки боссов акурат над ними же на карте.
