### ISSUE TITLE
Не в тему, но личку я тут не нашел.

### ISSUE THREAD

**Issue by gamer4eg** [laytya/Atlas#3]
Есть такое аддон BetterCharterStats, он показывает статы как на личе.
Попросил автора добавить вкладку с СПД(по строчке каждую школу магии и еще строчку +хила)
На что автор сказал что не знает где ловить эти значения.
Мб поможешь ему?
https://github.com/yutsuku/BetterCharacterStats/issues/1

И второе. Есть такой аддон AVR Который позволяет РИСОВАТЬ в мире. Был выпущен под 3.3.3 и тут же запрещен близами. Мб возьмешься за его бекпорт? Облегчи жизнь РЛам и шамам(радиус тотемов например).
Ссылка https://www.wowace.com/projects/avr

**Comment by laytya** [comment]
AVR не будет тут работать. нет таких функций в клиенте.

Про BCS - я скорее всего тоже не помогу, Ибо сам хз где их взять.
